export default {
    plural: {
        passengers: ['пассажир', 'пассажира', 'пассажирів'],
        days: ["день", "дні", "днів"],
        hours: ["година", "години", "годин"],
        minutes: ["хвилина", "хвилини", "хвилин"],
        seconds: ["секунда", "секунди", "секунд"]
    },
    errors: {
        server: {
            default: {
                title: "Ой, щось пішло не так",
                description: "Будь ласка, спробуйте ще раз через 30 секунд"
            }
        }
    },
    validation: {
        enterCorrectPhoneNumber: "Вкажіть коректний номер телефону",
        enterCorrectEmail: "Вкажіть коректну email-адресу",
        mustBeCompleted: "Обов'язково має бути заповнено"
    },
    pageNotFound: "Сторінку не знайдено",
    viewAll: "Переглянути все",
    view: "Переглянути",
    all: "Все",
    privateData: "Персональні дані",
    personalData: "Персональна інформація",
    attentionToThisItems: "Зверніть увагу",
    contacts: "Контакти",
    next: "Далі",
    back: "Назад",
    exit: "Вихід",
    hotline: "Гаряча лінія",
    phone: "Телефон",
    description: "Опис",
    loginOrRegistration: "Вхід/Реєстрація",
    logIn: "Увійти",
    aboutUs: "Про нас",
    hideText: "Приховати текст",
    readMore: "Читати далі",
    readAnother: "Читати ще",
    readAll: "Читати все",
    save: "Зберегти",
    cancel: "Відміна",
    edit: "Редагувати",
    name: "Ім'я",
    lastName: "Прізвище",
    middleName: "По батькові",
    birthday: "Дата народження",
    citizenship: "Громадянство",
    gender: "Стать",
    ru: "Російська",
    ua: "Українська",
    male: "Чоловіча",
    female: "Жіноча",
    change: "Змінити",
    show: {
        default: "Показати",
        more: "Показати ще",
        all: "Показати все",
        less: "Приховати"
    },
    quantity: "Кількість",
    from: "Від",
    amount: "Сума",
    forAmount: "На суму",
    payment: "Оплата",
    total: "Разом",
    checkout: "Оформити замовлення",
    learnMore: "Дізнатись більше",
    send: "Відправити",
    moreDetails: "Детальніше",
    sort: "Сортувати",
    reset: "Скинути",
    clear: "Очистити",
    clearList: "Очистити список",
    yourName: "Ваше ім'я",
    yourEmail: "Ваш e-mail",
    yourPhone: "Ваш телефон",
    frequentlyAskedQuestions: "Поширені запитання",
    howItWorks: "Як це працює?",
    ascendingPrice: "За зростанням ціни",
    descendingPrice: "За зменшенням ціни",
    youChoose: "Ви обрали",
    warning: "Увага",
    buy: "Купити",
    toBasket: "Перейти в кошик",
    toBuyer: "Покупцеві",
    filter: "Фільтр",
    filters: "Фільтри",
    price: "Ціна",
    priceFor: "Ціна на",
    prices: "Ціни",
    emptySearchResult: "Нічого не знайдено, спробуйте змінити запит",
    select: "Виберіть",
    selectYourGender: "Вкажіть вашу стать",
    apply: "Застосувати",
    accept: "Прийняти",
    removeSelection: "Скинути вибір",
    delete: "Видалити",
    toHomePage: "Перейти на головну",
    found: "Знайдено",
    free: "Безкоштовно",
    currency: {
        uah: "грн"
    },
    download: "Завантажити",
    conditions: "Умови",
    priceFrom: "Цiна вiд",
    priceTo: "Цiна до",
    supportService: "Служба підтримки",
    home: "Головна",
    allSearchResults: "Всі результати пошуку",
    informed: "Ознайомлений",
    asList: "Списком",
    transfers: "Пересадки",
    inTransit: "В дорозі"
};
