export default {
    plural: {
        passengers: ['пассажир', 'пассажира', 'пассажиров'],
        days: ['день', 'дня', 'дней'],
        hours: ['час', 'часа', 'часов'],
        minutes: ['минута', 'минуты', 'минут'],
        seconds: ['секунда', 'секунды', 'секунд']
    },
    errors: {
        server: {
            default: {
                title: "Ой, что-то пошло не так",
                description: "Пожалуйста, повторите попытку через 30 секунд"
            }
        }
    },
    validation: {
        enterCorrectPhoneNumber: "Укажите корректный номер телефона",
        enterCorrectEmail: "Укажите корректный email-адрес",
        mustBeCompleted: "Обязательно должно быть заполнено"
    },
    pageNotFound: "Страница не найдена",
    viewAll: "Смотреть все",
    view: "Смотреть",
    all: "Все",
    privateData: "Личные данные",
    personalData: "Персональная информация",
    attentionToThisItems: "Обратите внимание",
    contacts: "Контакты",
    next: "Далее",
    back: "Назад",
    whereTo: "Куда",
    fromWhere: "Откуда",
    thitherward: "Туда",
    backward: "Обратно",
    exit: "Выход",
    hotline: "Горячая линия",
    phone: "Телефон",
    description: "Описание",
    loginOrRegistration: "Вход/Регистрация",
    logIn: "Войти",
    aboutUs: "О нас",
    hideText: "Скрыть текст",
    readMore: "Читать далее",
    readAnother: "Читать ещё",
    readAll: "Читать всё",
    save: "Сохранить",
    cancel: "Отмена",
    edit: "Редактировать",
    name: "Имя",
    lastName: "Фамилия",
    middleName: "Отчество",
    birthday: "Дата рождения",
    citizenship: "Гражданство",
    gender: "Пол",
    male: "Мужской",
    female: "Женский",
    ru: "Русский",
    ua: "Украинский",
    change: "Изменить",
    show: {
        default: "Показать",
        more: "Показать ещё",
        all: "Показать все",
        less: "Скрыть"
    },
    quantity: "Количество",
    from: "От",
    amount: "Сумма",
    forAmount: "На сумму",
    payment: "Оплата",
    total: "Итого",
    checkout: "Оформить заказ",
    learnMore: "Узнать подробнее",
    send: "Отправить",
    moreDetails: "Подробнее",
    sort: "Сортировать",
    reset: "Сбросить",
    clear: "Очистить",
    clearList: "Очистить список",
    yourName: "Ваше имя",
    yourEmail: "Ваш e-mail",
    yourPhone: "Ваш телефон",
    frequentlyAskedQuestions: "Часто задаваемые вопросы",
    howItWorks: "Как это работает?",
    ascendingPrice: "По возрастанию цены",
    descendingPrice: "По убыванию цены",
    youChoose: "Вы выбрали",
    warning: "Внимание",
    buy: "Купить",
    toBasket: "Перейти в корзину",
    toBuyer: "Покупателю",
    filter: "Фильтр",
    filters: "Фильтры",
    price: "Цена",
    priceFor: "Цена на",
    prices: "Цены",
    emptySearchResult: "Ничего не найдено, попробуйте изменить запрос",
    select: "Выбрать",
    selectYourGender: "Укажите ваш пол",
    apply: "Применить",
    accept: "Принять",
    removeSelection: "Сбросить выбор",
    delete: "Удалить",
    toHomePage: "Перейти на главную",
    found: "Найдено",
    free: "Бесплатно",
    currency: {
        uah: "грн"
    },
    download: "Скачать",
    conditions: "Условия",
    priceFrom: "Цена от",
    priceTo: "Цена до",
    supportService: "Служба поддержки",
    home: "Главная",
    allSearchResults: "Все результаты поиска",
    informed: "Ознакомлен",
    asList: "Списком",
    transfers: "Пересадки",
    inTransit: "В пути",
    oneWayFlight: "Рейс в одну сторону",
    roundTripFlight: "Рейс в обе сторону",
    adult: "Взрослый",
    child: "Ребенок",
    baby: "Младенец",
    ticketRules: "Правила билетов",
    economy: "Эконом",
    comfort: "Комфорт",
    business: "Бизнес",
    toFind: "Найти",
    departureAndArrivalTime: "Время вылета и прибытия",
    departureFromTheCity: "Вылет из {0}",
    arrivalInTheCity: "Прибытие в {0}",
};
